### ISSUE TITLE
Bugs in the new stack realloc handling code

### ISSUE THREAD

**Issue by snicolai-blog** [MikeSteglich/Cmpl2#8]
With the following patch:
```
diff --git a/src/Modules/Interpreter/ExecContext.cc b/src/Modules/Interpreter/ExecContext.cc
index 18c4198..f898733 100755
--- a/src/Modules/Interpreter/ExecContext.cc
+++ b/src/Modules/Interpreter/ExecContext.cc
@@ -900,6 +900,7 @@ namespace cmpl
                     if (ac == 1) {
                         sveNo = svNo1 = replaceListOnStack(stackCur()) - _stack;
                         svNo2 = -1;
+                        printf("going to dereference 2 before the stack\n");
                     }
                     else {
                         svNo2 = replaceListOnStack(stackCur()) - _stack;
@@ -914,6 +915,7 @@ namespace cmpl
                 }
                 else {
                     sveNo = svNo1 = svNo2 = -1;
+                    printf("going to dereference 1 & 2 before the stack\n");
                 }
 
                 // execute operation
```

I get this error when running the enclosed cmpl file.

```
going to dereference 2 before the stack
=================================================================
==33313==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00010c101258 at pc 0x0001050eb3c4 bp 0x00016aec9f60 sp 0x00016aec9f58
READ of size 4 at 0x00010c101258 thread T0
    #0 0x1050eb3c0 in cmpl::CmplVal::isSpecial() const CmplVal.hh:482
    #1 0x105371ea0 in cmpl::StackValue::isSimple() StackValue.hh:104
    #2 0x105358f48 in cmpl::StackValue::simpleValue() StackValue.hh:92
    #3 0x1053c6098 in cmpl::StackValue::simpleValueOrEmptyArr(cmpl::CmplVal*) StackValue.hh:99
    #4 0x1053c316c in cmpl::OperationBase::execOper(cmpl::ExecContext*, cmpl::CmplVal&, bool&, unsigned int, unsigned short, bool, unsigned short, cmpl::StackValue*, cmpl::StackValue*) OperationBase.cc:68
    #5 0x105350f8c in cmpl::ExecContext::execCodeOperation(cmpl::IntCode::IcElem*) ExecContext.cc:922
    #6 0x1053447ac in cmpl::ExecContext::run(unsigned int, bool, cmpl::CmplVal*) ExecContext.cc:346
    #7 0x10539531c in cmpl::Interpreter::execCode() Interpreter.cc:635
    #8 0x105392ec0 in cmpl::Interpreter::run() Interpreter.cc:276
    #9 0x104fb0d38 in cmpl::MainControl::run() MainControl.cc:263
    #10 0x104fab588 in cmpl::MainControl::run(cmpl::CmdLineOptList*) MainControl.cc:164
    #11 0x104f35a84 in cmpl::Start::run(cmpl::CmdLineOptList*, cmpl::MainData*) Start.cc:124
    #12 0x104f3561c in main Start.cc:52
    #13 0x1073990f0 in start+0x204 (dyld:arm64e+0x50f0)

0x00010c101258 is located 40 bytes to the left of 1200-byte region [0x00010c101280,0x00010c101730)
allocated by thread T0 here:
    #0 0x1077927c8 in wrap__Znam+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4a7c8)
    #1 0x1053400c4 in cmpl::ExecContext::ExecContext(cmpl::Interpreter*, cmpl::ExecContext*, bool, cmpl::StackValue*) ExecContext.cc:77
    #2 0x10534102c in cmpl::ExecContext::ExecContext(cmpl::Interpreter*, cmpl::ExecContext*, bool, cmpl::StackValue*) ExecContext.cc:63
    #3 0x1053952b8 in cmpl::Interpreter::execCode() Interpreter.cc:632
    #4 0x105392ec0 in cmpl::Interpreter::run() Interpreter.cc:276
    #5 0x104fb0d38 in cmpl::MainControl::run() MainControl.cc:263
    #6 0x104fab588 in cmpl::MainControl::run(cmpl::CmdLineOptList*) MainControl.cc:164
    #7 0x104f35a84 in cmpl::Start::run(cmpl::CmdLineOptList*, cmpl::MainData*) Start.cc:124
    #8 0x104f3561c in main Start.cc:52
    #9 0x1073990f0 in start+0x204 (dyld:arm64e+0x50f0)

SUMMARY: AddressSanitizer: heap-buffer-overflow CmplVal.hh:482 in cmpl::CmplVal::isSpecial() const
Shadow bytes around the buggy address:
  0x0070218401f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007021840200: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007021840210: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007021840220: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x007021840230: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x007021840240: fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa fa
  0x007021840250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007021840260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007021840270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007021840280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007021840290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==33313==ABORTING
```

When 
```
                // execute operation
                if (!OperationBase::execOper(this, _opRes, transp, cd->se, cd->v.c.minor, (bool)(cd->v.c.par & ICPAR_OPER_CMP_FOLLOW), ac, _stack + svNo1, _stack + svNo2)) {
```

is called, the -1 assigned to `svNo1` or `svNo2` creates pointers before the `_stack` array.  These get evaluated at the beginning of execOper()

```
    bool OperationBase::execOper(ExecContext *ctx, CmplVal& res, bool& tp, unsigned se, unsigned short op, bool cmpFollow, unsigned short ac, StackValue *a1, StackValue *a2)
    {
        PROTO_MOD_OUTL(ctx->modp(), "exec operation: " << op << " (" << cmpFollow << "): " << ac);

        CmplVal resDs;
        MatrixMultMode mm = matrixMultNone;
        CmplVal nl(TP_NULL);
        CmplVal *a1s = (a1 ? a1->simpleValueOrEmptyArr(&nl) : NULL);
        CmplVal *a2s = (a2 ? a2->simpleValueOrEmptyArr(&nl) : NULL);
```
Looks like the proper thing to do is pass NULL when `svNo1` or `svNo2` is -1.  And testing that theory, the following patch fixes the issue:

```
diff --git a/src/Modules/Interpreter/ExecContext.cc b/src/Modules/Interpreter/ExecContext.cc
index 18c4198..58ce0f0 100755
--- a/src/Modules/Interpreter/ExecContext.cc
+++ b/src/Modules/Interpreter/ExecContext.cc
@@ -917,7 +917,7 @@ namespace cmpl
                 }
 
                 // execute operation
-                if (!OperationBase::execOper(this, _opRes, transp, cd->se, cd->v.c.minor, (bool)(cd->v.c.par & ICPAR_OPER_CMP_FOLLOW), ac, _stack + svNo1, _stack + svNo2)) {
+                if (!OperationBase::execOper(this, _opRes, transp, cd->se, cd->v.c.minor, (bool)(cd->v.c.par & ICPAR_OPER_CMP_FOLLOW), ac, (svNo1 != -1) ? _stack + svNo1 : NULL, (svNo2 != -1) ? _stack + svNo2 : NULL)) {
                     //TODO: sonstige Operation, insbesondere vielleicht in Codeblockheader (oder vielleicht doch gar nichts hier?)
                     // (fuer Transpose bei eindimensionalem Arrays hier weiter nichts zu tun, schon durch transp erledigt)
                     pushRes = false;
```

[ssincome_func.cmpl.txt](https://github.com/MikeSteglich/Cmpl2/files/7922463/ssincome_func.cmpl.txt)
.

**Comment by tschleiff** [comment]
You're right. I use -1 as indicator for no value, but missed the check for it. I corrected the line as you proposed.
